#!/bin/bash
# export MEMCACHE_SERVERS="memcached.trifecta.com"
# export MEMCACHE_USERNAME="cacheuser"
# export MEMCACHE_PASSWORD="trifecta00"
export MEMCACHE_SERVERS="localhost"
export MEMCACHE_USERNAME="myname"
export MEMCACHE_PASSWORD="mypass"
export CLOUDANT_URL="http://localhost:5984"
export RABBITMQ_URL="amqp://localhost/"
export DATABASE_URL="postgres://heroku:heroku@localhost/heroku-lightrate"
export SHARED_DATABASE_URL="postgres://heroku:heroku@localhost/heroku-lightrate"